version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sbt assembly
artificats:
  files:
    - target/scala-2.13/amazon-zio-messing-assumbly-0.1.0-SNAPSHOT.jar